name: js-release-date

on:
  push:
    paths:
      - '.github/workflows/js-release.yml'
      - 'docs/js-ide/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set release date
        run: echo "RELEASE_DATE=$(date -u +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Inject release date into js-release.js
        run: |
          sed -i "s/const RELEASE_DATE = \".*\";/const RELEASE_DATE = \"${RELEASE_DATE}\";/g" docs/js-ide/js-release.js

      - name: Commit updated js-release.js
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/js-ide/js-release.js

          if ! git diff --cached --quiet; then
            msg=$(git log -1 --pretty=%s --no-merges)
            if [ -z "$msg" ]; then
              msg=$(git log -1 --pretty=%s)
            fi
            git commit -m "release: ${msg}"
            git push
          else
            echo "No changes to commit"
          fi
